dbt_proj:
  outputs:

    dev:
      type: postgres
      threads: 1
      host: 192.168.1.108
      port: 5432
      user: user
      pass: password123
      dbname: warehouse
      schema: staging

  target: dev
